using System;
namespace EnetPluseClientApi.DTO.Static
{
    public enum OutcomeScope
    {
        OrdinaryTime = 1,
        OrdinaryTimeWithExtra,
        FullEvent,
        FirstHalf,
        SecondHalf,
        FirstQuarter,
        SecondQuarter,
        ThirdQuarter,
        FourthQuarter,
        FirstSet,
        SecondSet,
        ThridSet,
        FourthSet,
        FifthSet,
        FirstRound,
        SecondRound,
        ThirdRound,
        FourthRound,
        FifthRound,
        SixthRound,
        FirstInning,
        SecondInning,
        ThridInning,
        FouthInning,
        FifthInning,
        SixthInning,
        SeventhInning,
        EighthInning,
        NinthInning,
        First5Inning,
        Map1,
        Map2,
        Map3,
        Map4,
        Map5,
        Map6,
        Map7,
        FirstPeriod,
        SecondPeriod,
        ThirdPeriod
    }
}
