using System;
namespace EnetPluseClientApi.DTO.Static
{
    public enum ResultType
    {
        OrdinaryTime = 1,
        Extratime,
        Penaltyshootout,
        Finalresult,
        Halftime,
        Runningscore,
        Strokes_r1 = 31,
        Strokes_r2,
        Strokes_r3,
        Strokes_r4,
        Strokes_r5,
        Par,
        Position,
        Made_cut,
        Mpscore,
        Weight,
        Period1 = 51,
        Period2,
        Period3,
        Quarter1 = 60,
        Quarter2,
        Quarter3,
        Quarter4,
        Set1 = 80,
        Set2,
        Set3,
        Set4,
        Set5,
        Setswon,
        Tiebreak1,
        Tiebreak2,
        Tiebreak3,
        Tiebreak4,
        Tiebreak5,
        Gamescore,
        Set6,
        Set7,
        Rank = 100,
        Duration,
        Points,
        Distance,
        Comment,
        Laps = 221,
        Laps_behind,
        Pitstops,
        Inning1 = 301,
        Inning2,
        Inning3,
        Inning4,
        Inning5,
        Inning6,
        Inning7,
        Inning8,
        Inning9,
        Extra_inning,
        Hits,
        Errors,
        Misses,
        Horseracingodds =401,
        Startnumber = 408,
        Medal = 501,
        Missed_shots,
        Additional_shots,
        Tries,
        FourPoints,
        SixPoints,
        Overs,
        Extra,
        Wickets,
        Secondpoints,
        Secondovers,
        Secondextra,
        Secondwickets,
        Speed,
        Jump_off_penalties,
        Jump_off_time,
        Netpoints,
        Drawnumber,
        Official_rating,
        Form,
        Age,
        Fastest_lap_point,
        Handicap,
        Place_win,
        Allowance,
        Strokes_points_r1,
        Strokes_points_r2,
        Strokes_points_r3,
        Strokes_points_r4,
        Strokes_points_r5,
        Wins,
        Rides,
        Best_time
    }
}
